// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Todo.Infrastructure.Persistence;

namespace Todo.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200729200941_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Todo.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstimatedCompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8419d158-65f0-4978-b279-9b870c1d2b3a"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "You do it like a hive",
                            EstimatedCompletionTime = new DateTime(2020, 8, 1, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2357),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "I like the way you drive"
                        },
                        new
                        {
                            Id = new Guid("a67906bc-2f3a-435e-a965-7d96a1322bd3"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Imagine all the people",
                            EstimatedCompletionTime = new DateTime(2020, 7, 31, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2747),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "I want to hold your mug"
                        },
                        new
                        {
                            Id = new Guid("55d25821-16f7-428b-8a25-de1367cfa561"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Blue fire engine, blue fire engine",
                            EstimatedCompletionTime = new DateTime(2020, 8, 3, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2762),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 2,
                            Title = "All you need is global domination"
                        },
                        new
                        {
                            Id = new Guid("692c9781-8dd3-44b4-9cd9-6ef9bdb547ed"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "I think you'll understand",
                            EstimatedCompletionTime = new DateTime(2020, 8, 5, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2765),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Title = "We all live in our violet coach"
                        },
                        new
                        {
                            Id = new Guid("fb97d138-a22d-413a-b8cf-5ccd1962729b"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "But I'm not the only one",
                            EstimatedCompletionTime = new DateTime(2020, 8, 10, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2766),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Title = "Above us only poker chips"
                        },
                        new
                        {
                            Id = new Guid("f363c032-1ebe-4d0c-af42-8f20b8bd3183"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oh yeah!",
                            EstimatedCompletionTime = new DateTime(2020, 8, 13, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2807),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 1,
                            Title = "You'll let me learn to fly"
                        },
                        new
                        {
                            Id = new Guid("5baf1d63-a9fa-4c84-9462-edd19cfa46f8"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "And I'm gonna move your key",
                            EstimatedCompletionTime = new DateTime(2020, 8, 8, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2819),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 0,
                            Title = "I never thought I'd see that stick"
                        },
                        new
                        {
                            Id = new Guid("f0e46c6c-01be-4320-b757-f9da53005917"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Yea, yaz, in a Houston state of mind",
                            EstimatedCompletionTime = new DateTime(2020, 8, 5, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2821),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 0,
                            Title = "The joystick drops deep as does my light"
                        },
                        new
                        {
                            Id = new Guid("5a4fca27-0652-41ad-8295-5a9f7a0eede1"),
                            Completed = false,
                            Created = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "In a Houston state of mind",
                            EstimatedCompletionTime = new DateTime(2020, 8, 7, 20, 9, 41, 105, DateTimeKind.Utc).AddTicks(2823),
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = 0,
                            Title = "I never snooze, 'cause to snooze is the husband of site"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
